### PR TITLE
port changes from Scala 3 migration to Cats Effect 2 branch

### PR DESCRIPTION
**Pull request by kpodsiad**
The main reason to port https://github.com/evolution-gaming/scache/pull/221 is to keep sources as closest as possible. In mentioned PR, `CacheOpsCompat` was created to patch issues with Scala 3 compiler. This PR ports scala-2 structure of mentioned compat.

### CODE REVIEW

**Comment by kpodsiad** [comment]
https://github.com/evolution-gaming/scache/actions/runs/5441751004/jobs/9896073594?pr=224: `-1474736480 did not equal -1474636480 (CacheSpec.scala:1487)` - interesting 🤔

**Comment by kpodsiad** [comment]
failing test passes locally, but some other one fails randomly. is it a known issue that tests are flaky or is it my PR which maked them such?

**Comment by i-surkov** [comment]
> failing test passes locally, but some other one fails randomly. is it a known issue that tests are flaky or is it my PR which maked them such?

I think I've encountered it before

**Comment by kpodsiad** [comment]
@i-surkov Do you have any suggestion how to deal with thids problem? I don't know codebase, debugging what's going on isn't appealing to me. I can retrigger actions until one lucky leaves CI in green state but having to repeat that after each release doesn't sounds good for person who will be doing that

**Comment by i-surkov** [comment]
Flaky test is fixed in #226

**Review by i-surkov — APPROVED** [review]

**Pull request merged**
